(function(){
  function has(s,re){return re.test(String(s||''));}
  function explainPoint(point, section, chapter){
    const p=String(point||''); const t=(String(section?.title||'')+' '+p).toLowerCase();
    if(has(t,/sole trader|partnership|corporation|separate legal/)) return 'The legal form matters because it changes who owns the residual interest and who can be responsible for obligations. In accounting, however, the reporting entity still keeps its own records: business assets, liabilities, revenues, and expenses are not mixed with an owner’s personal transactions. When solving questions, separate the legal-liability issue from the accounting-entity issue.';
    if(has(t,/monetary unit/)) return 'The monetary-unit assumption is a recording filter. Accounting does not claim that non-monetary matters such as employee skill or customer loyalty are unimportant; it means ordinary accounting records require a monetary measure before an item can be recognized numerically. This is why some economically important facts appear in narrative disclosures rather than as account balances.';
    if(has(t,/economic.*entity|business entity/)) return 'Treat the business as the unit whose financial statements are being prepared. Ask: “Did the entity receive a resource, incur an obligation, earn revenue, or consume a resource?” If the event belongs only to the owner personally, it is not a business transaction. This prevents personal spending from distorting business profit and financial position.';
    if(has(t,/time period|reporting period/)) return 'A business may continue for many years, but users need information before the business ends. The time-period assumption divides that long life into months, quarters, or years. Once periods are created, timing becomes essential: revenue and expenses must be assigned to the correct period, which is why adjusting entries are necessary.';
    if(has(t,/going concern/)) return 'Going concern supports measurements that assume the entity will continue normal operations rather than liquidate immediately. For example, equipment can be used and depreciated over its useful life instead of being treated as though it must be sold tomorrow. If continuation becomes doubtful, the assumptions behind measurement and disclosure may change.';
    if(has(t,/historical cost|fair value|current value|measurement/)) return 'Measurement answers “At what amount should the recognized item be reported?” Historical cost begins with transaction-based amounts and is usually easy to verify. Current or fair-value measures can provide more up-to-date information when the applicable accounting requirements call for them. Do not choose a measurement basis simply because one number looks more realistic; apply the basis required for the item and context.';
    if(has(t,/revenue recognition|revenue.*earned|earned revenue/)) return 'Revenue is linked to performance, not merely to cash collection. If the entity has performed the service or otherwise satisfied the earning condition in the course material, revenue can exist even if the customer pays later. Conversely, cash received before performance normally creates a liability first because the entity still owes goods or services.';
    if(has(t,/expense recognition|matching|resources are consumed|obligations incurred/)) return 'Expense recognition follows economic consumption or incurrence. Paying cash early may create a prepaid asset; paying cash late may settle an expense that was already recognized. The practical question is therefore “What benefit was used, or what obligation was incurred, during this reporting period?” rather than “Was cash paid?”';
    if(has(t,/full disclosure/)) return 'Recognition in the primary statements is not the whole reporting story. Users also need material information that explains the numbers, risks, policies, commitments, or unusual events. Full disclosure therefore works through both the financial statements and the accompanying notes.';
    if(has(t,/asset:/)) return 'An asset is about a present economic resource controlled by the entity because of a past event. “Resource” is broader than cash or physical objects: receivables and prepaid services can also qualify because they give the entity rights or future economic potential. In classification questions, focus on control and the remaining benefit at the reporting date.';
    if(has(t,/liability:/)) return 'A liability is a present obligation created by a past event that will require transfer of an economic resource. The key word is “present”: a vague plan to spend money later is not the same as an existing obligation. Accounts payable, salaries payable, notes payable, and unearned revenue illustrate different ways obligations can arise.';
    if(has(t,/equity:|residual interest/)) return 'Equity is not a separate pile of cash. It is the residual claim after liabilities are deducted from assets. That is why revenue and expenses affect equity through profit, owner contributions affect equity directly, and dividends reduce equity without being operating expenses.';
    if(has(t,/revenue\/income|revenue increases|service revenue|sales revenue/)) return 'Revenue increases equity because the entity has earned value through its activities, normally by increasing assets or reducing liabilities. A cash receipt is revenue only when it represents earned performance. Collection of an existing receivable changes the form of the asset but does not create a second revenue.';
    if(has(t,/expense decreases|expense reduces|expenses/)) return 'Expenses represent resources consumed or obligations incurred in generating operations during the period. They reduce profit and therefore reduce retained earnings/equity. Repaying loan principal or paying an old payable is not automatically an expense because the expense or liability may have been recognized earlier.';
    if(has(t,/income statement|profit or loss/)) return 'The income statement measures performance over a period. It accumulates revenues and expenses for that period and reports their net result. Because it is period-based, its heading uses wording such as “for the month/year ended …,” and its result later feeds into retained earnings.';
    if(has(t,/changes in equity|retained earnings/)) return 'The changes-in-equity or retained-earnings statement explains why equity changed between two dates. In the simplified course model, beginning retained earnings is increased by net income and reduced by dividends. This statement is the bridge between the income statement and the statement of financial position.';
    if(has(t,/statement of financial position|balance sheet/)) return 'The statement of financial position is a snapshot at a date, not a measure of activity over a period. It reports resources (assets), obligations (liabilities), and residual claims (equity). The accounting equation is therefore visible directly in this statement: total assets must equal total liabilities plus total equity.';
    if(has(t,/statement of cash flows|operating, investing, and financing/)) return 'The cash-flow statement explains actual changes in cash and cash equivalents during a period. It separates operating, investing, and financing activities so users can distinguish cash generated by core operations from cash used to acquire long-term resources or raised from lenders and owners. Profit alone cannot provide this information.';
    if(has(t,/basic equation|assets = liabilities|expanded.*equation/)) return 'The equation is a consistency model, not just a formula to memorize. Every recognized transaction changes at least two account effects in a way that keeps resources equal to the claims on those resources. The expanded version makes the drivers of equity visible so you can see separately how capital, revenue, expense, and dividends change owners’ residual interest.';
    if(has(t,/owner.*contribution|shareholder.*contribution|share capital/)) return 'Owner contributions are financing from owners, not revenue from customers. They increase assets and equity directly. Keeping this separate from revenue is essential because otherwise profit would be overstated whenever owners inject capital.';
    if(has(t,/dividend|distribution/)) return 'A dividend is a distribution of equity to owners. It reduces assets (when paid) and reduces retained earnings/equity, but it is not an expense of earning revenue. This distinction is a frequent exam trap because both expenses and dividends reduce equity for different reasons.';
    if(has(t,/recordable|accounts are affected|dual effect|transaction analysis/)) return 'Transaction analysis should come before debit/credit rules. First identify the economic event and the accounts affected; next decide whether each account increases or decreases; then verify the accounting equation. Only after that should you translate the effects into debits and credits. This sequence prevents “debit means plus” mistakes.';
    if(has(t,/debit|credit|normal balance/)) return 'Debit and credit describe the left and right sides of an account, not good/bad and not universal plus/minus signs. The normal balance is the side normally used to increase that account class. Assets, expenses, and dividends normally increase with debits; liabilities, equity, and revenues normally increase with credits. Contra accounts deliberately have the opposite normal balance of the related account.';
    if(has(t,/double-entry/)) return 'Double-entry records the complete dual effect of a transaction. Total debits must equal total credits for every entry, but equality alone does not guarantee correctness: the wrong accounts can still be used for equal amounts. Always combine the debit-credit check with an economic-substance check.';
    if(has(t,/journal|original entry|chronological/)) return 'The journal is the chronological record of transactions. A complete journal entry identifies the date, accounts, debit and credit amounts, and—when required—an explanation. Journalizing converts transaction analysis into formal accounting language before the amounts are organized by account in the ledger.';
    if(has(t,/ledger|t-account|post to/)) return 'Posting reorganizes information from chronological order into account-by-account order. The ledger lets you answer questions such as “What is the current Cash balance?” or “How much is still owed to suppliers?” An ending balance comes from the beginning balance plus increases minus decreases according to that account’s normal-balance rules.';
    if(has(t,/trial balance/)) return 'A trial balance lists ledger accounts and their balances at a point in the accounting process. Its main arithmetic check is total debit balances = total credit balances. It cannot detect every error: a completely omitted transaction, a correct entry posted twice, or an equal debit and credit to the wrong accounts may still leave the totals equal.';
    if(has(t,/adjusting entries exist|adjusting entries|adjustment/)) return 'Adjusting entries update accounts at period end so the financial statements reflect the correct period under accrual accounting. They deal with timing differences: cash and recognition do not always occur together. A useful diagnostic is to ask whether something has been consumed/earned/incurred by the reporting date but is not yet fully reflected in the accounts.';
    if(has(t,/prepaid expense/)) return 'A prepaid expense starts as an asset because the entity has paid for a future benefit. As time passes or the benefit is consumed, part of that asset no longer exists and becomes expense. The adjustment therefore increases Expense (debit) and decreases the Prepaid Asset (credit). The remaining asset equals the unused benefit after adjustment.';
    if(has(t,/unearned revenue/)) return 'Unearned revenue starts as a liability because cash was received before the entity earned it. As performance occurs, the obligation to the customer decreases and revenue is recognized. The adjustment debits Unearned Revenue and credits Revenue for the portion earned, leaving the unperformed portion as a liability.';
    if(has(t,/accrued revenue/)) return 'Accrued revenue is earned before cash is received or before the customer has been billed. The period has revenue because performance has occurred, and the entity also has a receivable. The adjustment increases an asset (debit Accounts Receivable/Accrued Revenue) and increases Revenue (credit).';
    if(has(t,/accrued expense|interest payable|salaries payable/)) return 'An accrued expense has been incurred even though cash has not yet been paid and the liability may not yet have been recorded. The adjustment debits Expense and credits a Payable. Interest accruals also require a time calculation: principal × annual rate × fraction of year outstanding.';
    if(has(t,/depreciation/)) return 'Depreciation allocates the depreciable cost of a long-lived asset over periods of use; it is not a direct attempt to update the asset to market value. The usual adjustment debits Depreciation Expense and credits Accumulated Depreciation, a contra-asset. Carrying amount equals the asset’s cost less related accumulated depreciation.';
    if(has(t,/worksheet/)) return 'The worksheet is an optional working tool that brings trial-balance amounts, adjustments, adjusted balances, and financial-statement columns together. It helps organize the accounting cycle, but it is not a journal or ledger. Formal adjusting and closing entries still need to be journalized and posted to the accounting records.';
    if(has(t,/temporary|permanent accounts/)) return 'Temporary accounts measure one period’s performance or distributions and must start the next period at zero. Revenues, expenses, and dividends are therefore closed. Permanent statement-of-financial-position accounts—assets, liabilities, and equity balances such as retained earnings—carry forward.';
    if(has(t,/closing entries/)) return 'Closing transfers the current period’s temporary-account effects into retained earnings and resets temporary accounts to zero. The traditional four-step sequence closes revenues to Income Summary, expenses to Income Summary, Income Summary to Retained Earnings, and dividends to Retained Earnings. Closing changes account organization, not the period’s already-determined profit.';
    if(has(t,/post-closing/)) return 'The post-closing trial balance is prepared after closing to confirm that permanent-account debit and credit balances still agree. Revenue, expense, and dividend accounts should be absent because they now have zero balances. It becomes a clean starting point for the next accounting period.';
    if(has(t,/correcting/)) return 'Correcting entries repair accounting errors; adjusting entries handle normal timing under accrual accounting. A correcting entry should remove the incorrect effect and record the correct effect, ideally as one net entry. A balanced trial balance does not eliminate the need for correction because many wrong entries still contain equal debits and credits.';
    if(has(t,/inventory cost|purchase of inventory|freight-in|purchase return/)) return 'Under the perpetual approach used in the course, Inventory is updated for costs necessary to bring goods to their location and condition for sale, subject to the specific freight terms and discounts. Purchase returns and purchase discounts reduce the recorded inventory cost. Always distinguish buyer-side inventory cost from seller-side delivery expense.';
    if(has(t,/sale of inventory|two effects|cost of goods sold/)) return 'A perpetual inventory sale has two economic effects: earning revenue from the customer and transferring the cost of inventory out of the business. That is why two entries are needed—one at selling price and one at inventory cost. Gross profit is the difference between net sales and cost of goods sold, not the cash collected.';
    if(has(t,/freight-out|fob destination|fob shipping/)) return 'FOB terms determine which party bears transportation responsibility in the classroom problems. Under FOB shipping point, the buyer normally bears freight and includes it in inventory cost. Under FOB destination, the seller normally bears delivery cost and records a selling/delivery expense. Read the shipping term before deciding which account to use.';
    if(has(t,/sales returns|allowance/)) return 'A sales return reverses all or part of the customer-facing sale and, under a perpetual system when goods are returned to inventory, also reverses the related cost flow. A sales allowance reduces the selling price without necessarily returning the goods, so it normally affects the sales side but not inventory/COGS. This distinction is highly testable.';
    if(has(t,/discount/)) return 'A sales or purchase discount rewards payment within the discount period. Compute the discount on the amount still subject to discount after relevant returns/allowances. On the seller side, Sales Discounts is a contra-revenue; on the buyer side under perpetual accounting, the discount reduces Inventory.';
    if(has(t,/perpetual vs periodic|perpetual inventory|periodic inventory/)) return 'The inventory system determines when inventory records and COGS are updated. Perpetual accounting updates Inventory and COGS continuously; periodic accounting waits until period end to determine COGS from beginning inventory, purchases, and ending inventory. This is separate from the cost-flow method such as FIFO or weighted average.';
    if(has(t,/fifo/)) return 'FIFO assigns the oldest available unit costs to cost of goods sold first. Treat inventory as cost layers: list the units and unit cost in chronological order, satisfy the sale from the oldest layer, then carry the unused newer layers into ending inventory. The accounting cost flow need not match the physical movement of individual items.';
    if(has(t,/weighted average|moving weighted/)) return 'A moving weighted-average system recomputes average unit cost after each purchase under perpetual records. Sales use the latest average that existed immediately before the sale. Do not recompute the average after a sale when no new purchase has occurred, because the remaining units retain the same average cost.';
    if(has(t,/ownership|consignment|goods shipped/)) return 'Inventory belongs to the entity that controls/owns the goods under the relevant transaction terms at the reporting date. Shipping terms and consignment arrangements matter because physical location alone does not determine ownership. Before costing ending inventory, first decide which goods belong in the count.';
    if(has(t,/inventory errors/)) return 'Ending inventory directly affects COGS through the inventory equation. If ending inventory is overstated, COGS is understated and current-period profit is overstated; the opposite occurs when ending inventory is understated. Because one period’s ending inventory becomes the next period’s beginning inventory, many errors reverse in the following period if not otherwise corrected.';
    if(has(t,/turnover|lower.*measurement|net realizable/)) return 'Inventory is not analyzed only by its dollar balance. Measurement rules prevent carrying inventory above recoverable amounts when required, while turnover and days-in-inventory ratios help evaluate how quickly stock moves. Ratios require context: a very high turnover can indicate efficiency or possible stock shortages.';
    if(has(t,/fraud|internal control/)) return 'Internal control is a system of policies and procedures designed to safeguard assets, improve reliability of records, promote efficiency, and encourage compliance. No system provides absolute assurance because human error, collusion, override, and cost-benefit limits remain. Strong controls combine authorization, segregation of duties, documentation, physical safeguards, and independent checks.';
    if(has(t,/cash receipts|cash disbursements|petty cash/)) return 'Cash is especially vulnerable, so control emphasizes prompt recording, restricted access, documentation, and independent verification. Petty cash is a controlled exception for small payments: vouchers explain the expenditures, and replenishment records the expenses while restoring the fund to its authorized amount.';
    if(has(t,/bank reconciliation/)) return 'Bank and book cash balances differ because each side may know about items the other side has not yet recorded. Reconciliation classifies differences into bank-side timing items (such as deposits in transit and outstanding checks) and book-side items (such as bank charges, interest, or errors). Only book-side reconciling items normally require journal entries by the company.';
    if(has(t,/accounts receivable/)) return 'Accounts receivable arise when revenue is earned on account. They are reduced when customers pay, when sales are returned/allowed, or when accounts are written off under the appropriate method. Collecting an existing receivable increases Cash and decreases Accounts Receivable; it does not create new revenue.';
    if(has(t,/uncollectible|doubtful|allowance/)) return 'The allowance method reports receivables at an expected collectible amount by pairing gross receivables with an allowance for doubtful accounts. A write-off uses the allowance and removes the specific receivable, so net realizable value is unchanged at that moment. Estimation adjusts the allowance to the required ending balance and affects bad-debt expense.';
    if(has(t,/notes receivable/)) return 'A note receivable is a formal written claim that often carries interest. Interest is computed as face value × annual interest rate × time. At maturity, the holder normally receives principal plus interest; if the note crosses a reporting date, accrued interest may have to be recognized before cash is collected.';
    if(has(t,/plant assets|machine price|initial machine cost/)) return 'The initial cost of a plant asset includes purchase price and expenditures necessary to acquire the asset and prepare it for intended use. Ordinary operating costs after the asset is ready for use are generally expenses unless they meet the criteria for capitalization in the course material. Correct classification matters because capitalization affects multiple periods through depreciation.';
    if(has(t,/disposal of plant assets|gain|loss/)) return 'At disposal, first update depreciation to the disposal date if needed, then compute carrying amount = cost − accumulated depreciation. Compare cash proceeds with carrying amount: proceeds above carrying amount create a gain; proceeds below create a loss. Remove both the asset cost and its accumulated depreciation from the books.';
    if(has(t,/natural resources|intangible/)) return 'Natural resources allocate cost through depletion based on extraction/usage, while finite-life intangible assets are generally allocated through amortization according to the applicable course rules. The common principle is systematic allocation of a capitalized cost over the periods or units that consume its economic benefit.';
    if(has(t,/current liability/)) return 'Current-liability classification focuses on obligations expected to be settled within the entity’s normal operating cycle or relevant short-term classification period. Current liabilities include trade payables, accrued obligations, short-term notes, taxes payable, current portions of longer-term debt, and unearned revenue when performance is due soon.';
    if(has(t,/payroll|taxes|notes/)) return 'Liabilities can arise from borrowing, purchasing on credit, employee services, taxes, or other obligations. For accrued payroll, the expense belongs to the period employees worked even if cash is paid later. Notes payable may also require separate interest accrual in addition to principal.';
    if(has(t,/bond|coupon|market yield/)) return 'A bond’s issue price reflects the relationship between its stated/coupon rate and the market yield demanded by investors. If the coupon rate equals market yield, price tends toward face value; below-market coupons lead to a discount and above-market coupons to a premium. The economic reason is that investors adjust the price to earn the market return.';
    if(has(t,/bond accounting|effective interest|redeem/)) return 'Bond accounting separates cash interest from interest expense when a discount or premium exists. Under the effective-interest approach, interest expense is based on carrying amount × market yield, while cash paid follows face value × stated rate. The difference amortizes the discount or premium and moves carrying amount toward face value by maturity.';
    if(has(t,/corporate form|issuing shares|share transactions/)) return 'Issuing shares is an owner-financing transaction. Cash or other contributed assets increase, and equity accounts increase; the proceeds are not revenue because they come from shareholders rather than operations. Corporate accounting also separates contributed capital from retained earnings generated by operations.';
    if(has(t,/preference|treasury shares/)) return 'Preference shares have contractual preferences specified in their terms, commonly relating to dividends or liquidation. Treasury shares are the corporation’s own shares reacquired from investors; the reacquisition reduces cash and total equity rather than creating an investment asset in the corporation itself.';
    if(has(t,/share split|stock split/)) return 'A share split changes the number of shares and per-share amounts without changing total assets, liabilities, or equity. It is therefore different from a cash dividend, which transfers assets to shareholders. A share dividend reallocates components of equity but also does not distribute cash at the declaration itself.';
    if(has(t,/debt investments|why companies invest/)) return 'Companies invest excess cash to earn returns, manage liquidity, or pursue strategic objectives. Debt investments create contractual interest and principal cash flows. Classification and measurement determine where interest, realized gains/losses, and unrealized fair-value changes are reported.';
    if(has(t,/share investments|significant influence|equity method/)) return 'Accounting for share investments depends partly on the investor’s level of influence. A passive investment may be measured at fair value under the applicable classification, while significant influence commonly leads to the equity method, under which the investor recognizes its share of the investee’s profit and reduces the investment for dividends received.';
    if(has(t,/unrealized|fair-value change|other comprehensive/)) return 'An unrealized change means the investment has not yet been sold, but its measured fair value changed. Where that change is reported depends on the investment classification and applicable IFRS treatment. The key exam skill is to separate cash receipts, realized disposal results, and period-end measurement changes.';
    if(has(t,/operating section|net income|indirect method/)) return 'The indirect operating section begins with accrual-basis net income and reconciles it to operating cash flow. Add back non-cash expenses such as depreciation, remove gains/losses that belong with investing cash flows, and then adjust for operating working-capital changes. The objective is not to recalculate profit; it is to remove accrual and non-operating effects from profit.';
    if(has(t,/working capital|accounts receivable.*subtract|accounts payable.*add/)) return 'Use the “cash lag” logic instead of memorizing signs. An increase in an operating asset such as Accounts Receivable or Inventory generally means cash is lower than accrual profit, so subtract it. An increase in an operating liability such as Accounts Payable generally means cash payment has been deferred, so add it. Reverse the signs for decreases.';
    if(has(t,/investing section|non-current assets|equipment carrying amount/)) return 'Investing cash flows normally involve acquiring and disposing of long-term assets and investments, plus lending/collecting principal where classified as investing in the course. Comparative balances alone may not reveal cash purchases or sale proceeds; use additional information, gains/losses, depreciation, and T-account reconciliations to solve for the cash amounts.';
    if(has(t,/financing section|debt and share capital|dividends/)) return 'Financing cash flows explain changes in borrowing and owner financing: issuing or repaying debt, issuing shares, and cash distributions to owners under the course classification. Reconcile beginning and ending debt/equity accounts with non-cash changes and income-related movements to isolate the actual cash financing flows.';
    if(has(t,/final reconciliation|cash-flow quality/)) return 'The final cash-flow statement must reconcile beginning cash to ending cash: operating + investing + financing = net change in cash. Interpretation should then ask where cash comes from and whether that pattern is sustainable. Strong operating cash generation is often important, but investing outflows can be healthy when they reflect productive expansion.';
    if(has(t,/horizontal|comparative analysis|sales rise/)) return 'Horizontal analysis measures change across time in both amount and percentage. Percentage change should be interpreted together with the absolute amount and the base-year size. Compare related items—such as sales and COGS—because different growth rates can reveal changes in margins or operating structure.';
    if(has(t,/liquidity ratio|current ratio|quick/)) return 'Liquidity ratios assess the ability to meet short-term obligations, but they summarize rather than prove cash availability. The current ratio includes all current assets; the quick ratio focuses on more liquid resources. Evaluate asset quality, timing, seasonality, and industry norms before concluding that a higher ratio is automatically better.';
    if(has(t,/profitability|roa|return/)) return 'Profitability ratios connect profit to sales, assets, or equity. Margin measures profit earned from each unit of sales, while turnover measures how efficiently assets generate sales. Return on assets combines these dimensions, so two firms can reach the same ROA through different business models.';
    if(has(t,/solvency|leverage|debt/)) return 'Solvency analysis focuses on long-term financial risk and the ability to service debt. Debt ratios show how much financing comes from creditors, while interest-coverage measures compare earnings capacity with interest obligations. Higher leverage can magnify returns but also increases fixed claims and refinancing risk.';
    if(has(t,/sustainable income|unusual|one-time/)) return 'Sustainable-income analysis separates recurring operating performance from items unlikely to repeat. A one-time gain may increase current profit but should not automatically be extrapolated into future earnings. Read notes and classifications to understand whether an item reflects core operations, estimation changes, disposal activity, or another unusual factor.';
    return 'Treat this point as part of a reasoning chain rather than an isolated definition. Identify the economic event or balance being described, classify the affected financial-statement element, determine whether it increases or decreases, and then connect that result to the appropriate account or statement. In calculations, write the relationship first and substitute numbers second; in journal questions, justify the account before choosing debit or credit.';
  }

  const chapterWhy={
    ch1:'This foundation chapter teaches the economic meaning behind accounting numbers. If you understand entity boundaries, recognition, the financial-statement elements, and the equation, later debit/credit rules become logical rather than memorized.',
    ch2:'This chapter translates economic effects into the recording system. The goal is to move consistently from transaction analysis → debit/credit → journal → ledger → trial balance.',
    ch3:'This chapter is about timing. Cash and accounting recognition frequently occur in different periods, so adjustments make revenues, expenses, assets, and liabilities reflect the reporting date correctly.',
    ch4:'This chapter completes one accounting period and prepares the records for the next. It connects the adjusted trial balance to financial statements, closing, and post-closing balances.',
    ch5:'Merchandising adds inventory and cost of goods sold to the service-company accounting cycle. Every sale now has both a revenue effect and a cost/inventory effect under perpetual accounting.',
    ch6:'Inventory costing determines how total goods available for sale are split between COGS and ending inventory. That split affects profit, assets, and ratios even when physical units are identical.',
    ch7:'Internal control explains how accounting information is protected and verified, especially for cash. The focus is not only recording transactions but designing procedures that make errors and fraud harder to occur or conceal.',
    ch8:'Receivables combine revenue recognition with collection risk and time value. You need to understand how claims arise, how expected credit losses are reflected, and how notes create interest.',
    ch9:'Long-lived assets provide benefits over multiple periods. The accounting challenge is deciding what to capitalize initially, how to allocate cost over use, and how to measure the result when assets are disposed of.',
    ch10:'Current liabilities connect short-term obligations with accrual accounting. Many questions test whether an expense or liability exists before cash payment.',
    ch11:'Non-current liabilities explain long-term borrowing and the time value embedded in bond prices and interest expense. Focus on the difference between face value, cash interest, carrying amount, and market yield.',
    ch12:'Corporate equity distinguishes owner contributions, retained earnings, distributions, and reacquired shares. These are equity transactions, not ordinary operating revenues or expenses.',
    ch13:'Investment accounting links cash returns, influence over investees, fair-value measurement, and presentation. Classification determines which measurement changes affect income or other comprehensive income.',
    ch14:'The cash-flow statement explains why profit is not the same as cash. The teacher flow is best learned as reconciliation: operating first, then investing and financing, then check beginning cash → ending cash.',
    ch15:'Financial-statement analysis converts raw statements into comparisons and ratios. The skill is interpretation: explain what changed, why it may have changed, and what limitation prevents a simplistic conclusion.'
  };

  function workedSteps(section){
    const t=String(section?.title||'').toLowerCase();
    if(has(t,/transaction analysis/)) return ['Identify whether the event belongs to the reporting entity and is recordable.','Name the accounts before thinking about debit or credit.','Mark each account ↑ or ↓ and classify it as asset, liability, equity, revenue, expense, or dividend.','Check A = L + E. Only then translate the effects into debit/credit if the question asks for an entry.'];
    if(has(t,/debit and credit|double-entry/)) return ['Start from the economic effect: which account increases or decreases?','Use the account class to determine its normal increase side.','Place increases/decreases on debit or credit accordingly.','Confirm total debits equal total credits and then re-check that the chosen accounts make economic sense.'];
    if(has(t,/journalize/)) return ['Analyze the transaction and select the accounts.','Enter the debit account(s) first with amounts in the debit column.','Indent the credit account(s) and enter equal credit amount(s).','Add date/reference/explanation when required, then verify Dr = Cr.'];
    if(has(t,/ledger/)) return ['Take each journal line separately.','Post the amount to the corresponding ledger account on the same debit/credit side.','Include date/reference so the posting can be traced.','Compute the account balance using its beginning balance and all posted changes.'];
    if(has(t,/trial balance/)) return ['List accounts and their ending ledger balances in the standard order used by the course.','Place each balance in either debit or credit column according to its ledger balance.','Total both columns and compare them.','If unequal, investigate posting/amount/side errors; if equal, remember some errors can still remain.'];
    if(has(t,/prepaid/)) return ['Determine the total prepaid amount and coverage period.','Compute how much benefit has expired by the adjustment date.','Recognize the expired part as expense and reduce the prepaid asset.','Compute the remaining asset as a final reasonableness check.'];
    if(has(t,/unearned/)) return ['Identify cash received before performance and the original liability.','Measure the portion of service now performed/earned.','Reduce Unearned Revenue for that earned portion and recognize Revenue.','Check that the remaining liability equals the unperformed portion.'];
    if(has(t,/accrued revenue/)) return ['Confirm the service/revenue has been earned by period end.','Confirm cash/billing has not yet produced a recorded receivable.','Record the receivable as an asset and recognize revenue in the current period.','Later collection should reduce the receivable, not create revenue again.'];
    if(has(t,/accrued expense|interest/)) return ['Identify the resource/service already consumed or interest already incurred.','Calculate the amount attributable to the current period.','Debit the relevant Expense and credit the Payable.','When cash is later paid, settle the liability and record only any new-period expense.'];
    if(has(t,/depreciation/)) return ['Determine depreciable base and the method/rate supplied by the question.','Calculate the current period’s depreciation only.','Debit Depreciation Expense and credit Accumulated Depreciation.','Check carrying amount = cost − accumulated depreciation; do not credit the asset account under the standard accumulated-depreciation presentation.'];
    if(has(t,/closing entries/)) return ['Close all revenue balances to Income Summary.','Close all expense balances to Income Summary.','Close the resulting Income Summary balance (net income or loss) to Retained Earnings.','Close Dividends to Retained Earnings and verify every temporary account is zero.'];
    if(has(t,/sales returns/)) return ['Identify whether goods are physically returned or only a price allowance is granted.','Reverse/reduce the sales-side amount using the contra-revenue account.','If goods are returned and can re-enter inventory under the perpetual setup, restore Inventory and reduce COGS for the cost amount.','Keep selling price and cost amount separate.'];
    if(has(t,/discount/)) return ['Determine the amount still subject to discount after returns/allowances.','Check whether payment occurs within the discount window.','Apply the stated percentage to the eligible amount.','Record the seller/buyer side using the appropriate contra-revenue or inventory treatment from the course.'];
    if(has(t,/fifo/)) return ['Write inventory layers in chronological order with units × unit cost.','For each sale, consume units from the oldest available layer first.','Sum the assigned layer costs to calculate COGS.','Carry the unused layers forward and verify units available − units sold = ending units.'];
    if(has(t,/weighted average/)) return ['After a purchase, compute total cost available ÷ total units available.','Use that current average for the next sale.','Reduce units and inventory cost by units sold × current average.','Recalculate only when another purchase changes the cost pool.'];
    if(has(t,/bank reconciliation/)) return ['Begin with separate bank and book balances.','Adjust the bank side for deposits in transit, outstanding checks, and bank errors.','Adjust the book side for charges, collections, interest, NSF items, and book errors.','Both adjusted balances must agree; journalize only the company-book adjustments.'];
    if(has(t,/notes receivable/)) return ['Identify face value, annual rate, and time outstanding.','Compute interest = principal × rate × time.','Determine whether the reporting date requires an interest accrual before maturity.','At maturity, distinguish principal collection from interest revenue.'];
    if(has(t,/disposal/)) return ['Update depreciation to the disposal date when required.','Compute carrying amount = cost − accumulated depreciation.','Compare proceeds with carrying amount to find gain or loss.','Remove asset cost and accumulated depreciation, record cash proceeds, and record the balancing gain/loss.'];
    if(has(t,/bond accounting|bonds and market/)) return ['Compare stated coupon rate with market yield to understand price direction.','Separate cash interest (face × stated rate) from interest expense (carrying amount × market yield when applicable).','Use the difference to amortize discount/premium.','Check that carrying amount moves toward face value as maturity approaches.'];
    if(has(t,/operating section/)) return ['Start with net income.','Add back non-cash expenses and remove gains/losses whose cash effects belong elsewhere.','Adjust for changes in operating current assets and current liabilities.','The resulting amount is net cash provided/used by operating activities.'];
    if(has(t,/working capital/)) return ['Compute current-year minus prior-year change for each operating working-capital account.','For operating assets: increase = subtract; decrease = add.','For operating liabilities: increase = add; decrease = subtract.','Explain each sign using whether cash collection/payment lagged behind accrual recognition.'];
    if(has(t,/investing section/)) return ['Identify non-current asset/investment accounts that changed.','Use additional information to separate purchases, disposals, depreciation, and non-cash changes.','Solve for cash paid or received, often with a T-account reconciliation.','Report only cash portions in the cash-flow statement; disclose significant non-cash transactions separately.'];
    if(has(t,/financing section/)) return ['Identify debt and equity accounts that changed.','Separate cash issues/borrowings from non-cash changes and repayments.','Use retained-earnings reconciliation to infer dividends when needed.','Classify the resulting cash receipts/payments according to the course convention.'];
    if(has(t,/ratio|comparative|analysis/)) return ['Write the formula or comparison base before using numbers.','Substitute consistent-period amounts and calculate carefully.','Interpret the direction economically rather than stopping at the number.','State at least one limitation or contextual factor before concluding performance improved or worsened.'];
    return ['Extract the facts and identify exactly what the question is asking.','State the accounting rule or relationship before calculating or journalizing.','Apply the rule to the facts step by step; keep amounts and account classifications separate.','Perform a final check: equation balance, debit = credit, ending balance reconciliation, or reasonableness depending on the topic.'];
  }

  function activeRecall(section){
    const clean=String(section.title||'').replace(/^\d+\.\s*/,'').replace(/—.*$/,'').trim();
    const term=(section.terms&&section.terms[0])||clean;
    return [
      `Explain “${term}” in your own words without using the definition on screen.`,
      `Using the worked example, explain why the accounting treatment is correct and name the financial-statement element(s) affected.`,
      `What is the most likely exam trap in this section, and what check would prevent it?`
    ];
  }


  const reviewRefs={
    ch1:['Ch1 §1.1–1.2 Accounting Activities / Building Blocks','Ch1 §1.2 The Building Blocks of Accounting; Ch3 §3.1 for recognition timing','Ch1 §1.3 The Accounting Equation + financial-statement elements','Ch1 §1.5 Financial Statements; Ch14 §14.1 for cash flows','Ch1 §1.3 The Accounting Equation','Ch1 §1.4 Analyzing Business Transactions'],
    ch2:['Ch2 §2.1 Accounts, Debits, and Credits','Ch2 §2.1 Accounts, Debits, and Credits','Ch2 §2.2 The Journal','Ch2 §2.3 The Ledger and Posting','Ch2 §2.4 The Trial Balance','Ch2 §2.1–2.4 Recording Process'],
    ch3:['Ch3 §3.1 Accrual-Basis Accounting and Adjusting Entries','Ch3 §3.2 Adjusting Entries for Deferrals — Prepaid Expenses','Ch3 §3.2 Adjusting Entries for Deferrals — Unearned Revenues','Ch3 §3.3 Adjusting Entries for Accruals — Accrued Revenues','Ch3 §3.3 Adjusting Entries for Accruals — Accrued Expenses','Ch3 §3.2 Prepaid Expenses — Depreciation','Ch3 §3.4 Adjusted Trial Balance and Financial Statements'],
    ch4:['Ch4 §4.1–4.3 Worksheet, Closing, and Accounting Cycle','Ch4 §4.2 Closing the Books','Ch4 §4.2 Closing the Books — Preparing/Posting Closing Entries','Ch4 §4.2 Preparing a Post-Closing Trial Balance','Ch4 §4.3 Accounting Cycle and Correcting Entries'],
    ch5:['Ch5 §5.2 Recording Purchases Under a Perpetual System','Ch5 §5.3 Recording Sales Under a Perpetual System','Ch5 §5.2–5.3 Freight Terms / Freight Costs','Ch5 §5.3 Sales Returns and Allowances','Ch5 §5.2–5.3 Purchase/Sales Discounts','Ch5 §5.1 Merchandising Operations and Inventory Systems + periodic-system extension'],
    ch6:['Ch6 §6.1–6.2 Inventory Systems vs Costing Methods','Ch6 §6.2 Inventory Costing Methods — FIFO','Ch6 §6.2 Inventory Costing Methods — Average-Cost / Moving Average','Ch6 §6.1 Classifying and Determining Inventory','Ch6 §6.3 Effects of Inventory Errors','Ch6 §6.4 Inventory Statement Presentation and Analysis'],
    ch7:['Ch7 §7.1 Fraud and Internal Control','Ch7 §7.2 Cash Controls','Ch7 §7.3 Bank Account Controls / Bank Reconciliation','Ch7 §7.4 Reporting Cash'],
    ch8:['Ch8 §8.1 Recognition of Accounts Receivable','Ch8 §8.2 Valuation and Disposition of Accounts Receivable','Ch8 §8.3 Notes Receivable','Ch8 §8.4 Statement Presentation and Analysis of Receivables'],
    ch9:['Ch9 §9.1 Plant Asset Expenditures','Ch9 §9.2 Depreciation Methods','Ch9 §9.3 Plant Asset Disposals','Ch9 §9.4 Natural Resources and Intangible Assets'],
    ch10:['Ch10 §10.1 Current Liabilities','Ch10 §10.1 Current Liabilities — Notes, Taxes, Payroll','Ch10 §10.1 Current Liabilities — Unearned Revenues','Ch10 §10.2 Reporting and Analyzing Current Liabilities'],
    ch11:['Ch11 §11.1 Bonds Payable / Bond Pricing','Ch11 §11.2 Accounting for Bond Transactions','Ch11 §11.3 Other Non-Current Liabilities','Ch11 §11.4 Reporting and Analyzing Non-Current Liabilities'],
    ch12:['Ch12 §12.1 Corporate Form','Ch12 §12.2 Share Transactions / Treasury Shares','Ch12 §12.3 Dividends and Share Splits','Ch12 §12.4 Reporting and Analyzing Equity'],
    ch13:['Ch13 §13.1 Debt Investments','Ch13 §13.2 Share Investments','Ch13 §13.3 Valuing and Reporting Investments'],
    ch14:['Ch14 §14.1 Usefulness and Format of the Statement of Cash Flows','Ch14 §14.2 Preparing the Statement of Cash Flows — Indirect Method','Ch14 §14.2 Indirect Method — Changes in Operating Assets/Liabilities','Ch14 §14.2 Investing Activities / Non-Current Asset Reconciliations','Ch14 §14.2 Financing Activities / Debt and Equity Reconciliations','Ch14 §14.1–14.3 Cash Reconciliation and Evaluation'],
    ch15:['Ch15 §15.1 Basics of Financial Statement Analysis','Ch15 §15.2 Ratio Analysis — Liquidity','Ch15 §15.2 Ratio Analysis — Profitability','Ch15 §15.2 Ratio Analysis — Solvency','Ch15 §15.3 Sustainable Income']
  };
  window.AccountingDeepTheory={
    explainPoint,
    workedSteps,
    activeRecall,
    whyChapter:function(ch){return chapterWhy[ch.id]||'Connect the concept to the accounting flow, apply it to a concrete transaction, and verify the resulting account or statement effect.';},
    reviewRef:function(ch,section){const i=(ch.sections||[]).indexOf(section);return (reviewRefs[ch.id]&&reviewRefs[ch.id][i])||section.bookRef||ch.source;}
  };
})();
